#!/usr/bin/env node
/**
 * @fileoverview SessionStart hook that checks plugin dependencies.
 * Reads dependencies config (yaml/yml/json/jsonc) and verifies required plugins are installed.
 * Outputs a system message listing any missing dependencies with install commands.
 *
 * @description
 * This hook is executed at the start of each Claude Code session.
 * It parses the plugin's dependencies config file and checks against
 * the user's installed plugins registry to identify missing dependencies.
 *
 * @generated by anthropak
 * @see https://github.com/zrosenbauer/anthropak
 */
