#!/usr/bin/env node
/**
 * @fileoverview SessionStart and UserPromptSubmit hook that checks plugin dependencies.
 * Reads dependencies config (yaml/yml/json/jsonc) and verifies required plugins are installed.
 *
 * SessionStart: Full dependency check, outputs additionalContext with missing deps, caches result.
 * UserPromptSubmit: Reads cached result, blocks prompt submission if required deps are missing.
 *
 * @generated by anthropak
 * @see https://github.com/zrosenbauer/anthropak
 */
