# typed: false
# frozen_string_literal: true

# Homebrew formula for anthropak
# Auto-generated by scripts/generate-formula.ts
# Update SHA256 checksums after building binaries

class Anthropak < Formula
  desc "CLI tool to manage plugin dependencies for Claude Code plugins"
  homepage "https://github.com/zrosenbauer/anthropak"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zrosenbauer/anthropak/releases/download/v#{version}/anthropak-darwin-arm64"
      sha256 "aa1d1419583464ad306e539bcadbfc178024047df7685fe2e7a521910e4fdd39"
    else
      url "https://github.com/zrosenbauer/anthropak/releases/download/v#{version}/anthropak-darwin-x64"
      sha256 "0b6381ddccbb2fec179b274938718e1892b12f5908a8e62a73b5a0fec04f5975"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/zrosenbauer/anthropak/releases/download/v#{version}/anthropak-linux-arm64"
      sha256 "a03732d7f6f374eb6ec107cbe200a32088bc641e4df385147b742bc7ee885994"
    else
      url "https://github.com/zrosenbauer/anthropak/releases/download/v#{version}/anthropak-linux-x64"
      sha256 "34c945026bcb0b4907cf6d124db037414636cd01151ab31b83a74f8f58e40407"
    end
  end

  def install
    binary_name = if OS.mac?
                    Hardware::CPU.arm? ? "anthropak-darwin-arm64" : "anthropak-darwin-x64"
                  else
                    Hardware::CPU.arm? ? "anthropak-linux-arm64" : "anthropak-linux-x64"
                  end

    bin.install binary_name => "anthropak"
  end

  test do
    assert_match "anthropak", shell_output("#{bin}/anthropak --help")
  end
end
