#!/usr/bin/env bun
/**
 * Generates the Homebrew formula with correct SHA256 checksums.
 * Run this after building binaries to update Formula/anthropak.rb.
 */

import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const BIN_DIR = join(ROOT, "packages", "cli", "bin");
const CLI_PKG = join(ROOT, "packages", "cli", "package.json");
const FORMULA_DIR = join(ROOT, "Formula");
const FORMULA_PATH = join(FORMULA_DIR, "anthropak.rb");

const REPO = "zrosenbauer/anthropak";

interface Binary {
  name: string;
  os: "darwin" | "linux";
  arch: "arm64" | "x64";
}

const BINARIES: Binary[] = [
  { name: "anthropak-darwin-arm64", os: "darwin", arch: "arm64" },
  { name: "anthropak-darwin-x64", os: "darwin", arch: "x64" },
  { name: "anthropak-linux-arm64", os: "linux", arch: "arm64" },
  { name: "anthropak-linux-x64", os: "linux", arch: "x64" },
];

function sha256(filePath: string): string {
  const content = readFileSync(filePath);
  return createHash("sha256").update(content).digest("hex");
}

function getVersion(): string {
  const pkg = JSON.parse(readFileSync(CLI_PKG, "utf8"));
  return pkg.version;
}

function generateFormula(checksums: Map<string, string>, version: string): string {
  const darwinArm64 = checksums.get("anthropak-darwin-arm64") ?? "PLACEHOLDER";
  const darwinX64 = checksums.get("anthropak-darwin-x64") ?? "PLACEHOLDER";
  const linuxArm64 = checksums.get("anthropak-linux-arm64") ?? "PLACEHOLDER";
  const linuxX64 = checksums.get("anthropak-linux-x64") ?? "PLACEHOLDER";

  return `# typed: false
# frozen_string_literal: true

# Homebrew formula for anthropak
# Auto-generated by scripts/build-formula.ts

class Anthropak < Formula
  desc "CLI tool to manage plugin dependencies for Claude Code plugins"
  homepage "https://github.com/${REPO}"
  version "${version}"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/${REPO}/releases/download/v#{version}/anthropak-darwin-arm64"
      sha256 "${darwinArm64}"
    else
      url "https://github.com/${REPO}/releases/download/v#{version}/anthropak-darwin-x64"
      sha256 "${darwinX64}"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/${REPO}/releases/download/v#{version}/anthropak-linux-arm64"
      sha256 "${linuxArm64}"
    else
      url "https://github.com/${REPO}/releases/download/v#{version}/anthropak-linux-x64"
      sha256 "${linuxX64}"
    end
  end

  def install
    binary_name = if OS.mac?
                    Hardware::CPU.arm? ? "anthropak-darwin-arm64" : "anthropak-darwin-x64"
                  else
                    Hardware::CPU.arm? ? "anthropak-linux-arm64" : "anthropak-linux-x64"
                  end

    bin.install binary_name => "anthropak"
  end

  test do
    assert_match "anthropak", shell_output("#{bin}/anthropak --help")
  end
end
`;
}

function main(): void {
  console.log("Generating Homebrew formula...\n");

  const version = getVersion();
  console.log(`Version: ${version}`);

  // Check that binaries exist and calculate checksums
  const checksums = new Map<string, string>();
  let allExist = true;

  for (const binary of BINARIES) {
    const binaryPath = join(BIN_DIR, binary.name);
    if (existsSync(binaryPath)) {
      const hash = sha256(binaryPath);
      checksums.set(binary.name, hash);
      console.log(`${binary.name}: ${hash}`);
    } else {
      console.log(`${binary.name}: (not found, using placeholder)`);
      allExist = false;
    }
  }

  if (!allExist) {
    console.log('\nNote: Some binaries not found. Run "pnpm build:bin" to build them.');
  }

  // Generate and write formula
  mkdirSync(FORMULA_DIR, { recursive: true });
  const formula = generateFormula(checksums, version);
  writeFileSync(FORMULA_PATH, formula);
  console.log(`\nFormula written: ${FORMULA_PATH}`);
}

main();
